### ISSUE TITLE
gin.mangafox.images -> Error: Image not found

### ISSUE THREAD

**Issue by calgara12** [pikax/gin-downloader#11]
Hey, its me again :)

Since Yestserday i encounter the following error:

When i do:

```javascript

 gin.mangafox.images("One Piece", 1)
    .then(x=>{
        console.log('starting...')
        console.log('getting %d images', x.length);
        return x.map(p=>{

            p.then(r=>{
                //this will run as soon each promise is resolved
                //r contains url
                console.log(r);
            })
        });
    })
    .then(x=>Promise.all(x))
    .then(x=>console.log('resolved'))
    .catch(console.error);

```

It starts listing the images, until i get multiple errors saying: 
Error: Image not found and
(node:5880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I only encounter this error on specific mangas and chapters. for example the second chapter of one piece lists all images without the error, the first chapter of Berserk returns multiple errors.

I did not receive this error a couple days ago. When i visit mangafox, all pages of this manga seem to be online.

Thanks, and have a nice day!

**Comment by pikax** [comment]
Hey,

I think the issue is because mangafox has some licence mangas, one piece is one of them, if you are in USA you can't see the [first chapter](http://mangafox.me/manga/one_piece/v01/c001/)

it should show this error:
![image](https://user-images.githubusercontent.com/4620458/27536581-c26c61a6-5a67-11e7-9486-9eaefaa60f5b.png)

if that's the case I can't do much.

if you can access to the chapters via browser without proxy or VPN, it gin-downloader should work without an issue.

Can you tell me the country from you're accessing mangafox?

**Comment by calgara12** [comment]
I can access the first chapter of one piece without a problem. Im accessing it from Europe, Austria.

Thank you for your effort :)

**Comment by pikax** [comment]
It seems the One Piece is licence in Austria
![image](https://user-images.githubusercontent.com/4620458/27537483-ff5641a0-5a6b-11e7-97dc-d6a93004fcef.png)

I'm using a VPN and connected to Vienna

can you try other manga:
``` javascript
gin.mangafox.images("Tales of Demons and Gods", 1)
    .then(x=>{
        console.log('starting...')
        console.log('getting %d images', x.length);
        return x.map(p=>{

            p.then(r=>{
                //this will run as soon each promise is resolved
                //r contains url
                console.log(r);
            })
        });
    })
    .then(x=>Promise.all(x))
    .then(x=>console.log('resolved'))
    .catch(console.error);
```

**Comment by calgara12** [comment]
That is odd. Here is what i get when accessing one piece on mangafox:
![snip](https://user-images.githubusercontent.com/28657023/27538302-9488f8fc-5a77-11e7-8e83-ed087eb31181.PNG)

![op](https://user-images.githubusercontent.com/28657023/27538305-99e5bc04-5a77-11e7-9c2c-fe7a5007ac2c.PNG)

I also dont get an error when I try to download chapter 2,3, 666
When i try to get images of the first chapter of one piece i get this output: 
[output.txt](https://github.com/pikax/gin-downloader/files/1101998/output.txt)

The amount of "Error: Image not found" is variable. Sometimes i get 2, sometimes 4 and sometimes 10+

The pattern I've found was that i get the errors when the chapter has a lot of pages. For example, first chapter of one piece has 61 pages, First chapter of berserk has 89 pages.
Although it could just be that just the chance of an error occurance is higher the more pages are in the chapter.

Do you have an idea what's wrong here?

**Comment by pikax** [comment]
That's odd, I've just added a *licensed* field and throw an exception when is licensed, I can't publish now, I will publish at night.

I've just tried in UK, and it downloads the first chapter as expected.

I use [debug]('https://www.npmjs.com/package/debug') to be able to debug, to debug mangafox just use `gin-downloader:mangafox*`

```bash
#windows
set DEBUG=`gin-downloader:mangafox*` node index.js
#linux
DEBUG=`gin-downloader:mangafox*` node index.js
```

Can you send the log of that when it fails? 

Thank you

**Comment by pikax** [comment]
Just read your log, it seems the regex is failing to find the image.

You need to wait until next publish (tonight)  to be able to have a proper debug of the error.

Thank you :)

**Comment by calgara12** [comment]
Alright thanks ill wait. Could you give me a notice once you commit the update?

**Comment by pikax** [comment]
just manage to publish, can you update gin-downloader

and run with *DEBUG:gin-downloader:mangafox**

**Comment by calgara12** [comment]
Unfortunately i am unfamilliar with 'debug'... i assume you are talking about https://www.npmjs.com/package/debug

I installed this and i did set DEBUG=`gin-downloader:mangafox*`
then i ran "node app DEBUG:gin-downloader:mangafox*" and this was the output:
[output.txt](https://github.com/pikax/gin-downloader/files/1102270/output.txt)

not sure if i did that how im supposed to. i did not make any change in the code. As i said i am new to this. Just let me know if i should do something different.

**Comment by pikax** [comment]
create a new folder and place this two files in it:

package.json:
```json
{
  "name": "tess",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts":{
  	"start" :"cross-env DEBUG=gin-downloader:* node index"
  },
  "dependencies": {
    "cross-env": "^5.0.1",
    "gin-downloader": "^1.0.6"
  }
}

```

index.js
```javascript
var gin = require('gin-downloader')

gin.mangafox.images("One Piece", 1)
    .then(x=>{
        console.log('starting...')
        console.log('getting %d images', x.length);
        return x.map(p=>{

            p.then(r=>{
                //this will run as soon each promise is resolved
                //r contains url
                console.log(r);
            })
        });
    })
    .then(x=>Promise.all(x))
    .then(x=>console.log('resolved'))
    .catch(console.error);
```


- `npm install`
- `npm start`


save the output

**Comment by calgara12** [comment]
Thanks, here is my output: 
[output.txt](https://github.com/pikax/gin-downloader/files/1102493/output.txt)

**Comment by pikax** [comment]
Thank you, it seems the website is returning 
`503 Service Temporarily Unavailable` 

Mangafox uses rate-limit, if you do too many requests it will block some calls, I already retry automatically, the issue was the retry time was too short, I double it, it seems to be working, but not a definitive solution.

**Comment by calgara12** [comment]
Ok thanks, but after the update i still get the same error message...
[output.txt](https://github.com/pikax/gin-downloader/files/1102646/output.txt)

Or do you still have to commit the change?

**Comment by pikax** [comment]
it should have fix it.

can you tell me the version?

**Comment by calgara12** [comment]
1.0.7

I included the version in the output.txt in my last post

**Comment by pikax** [comment]
I will fix that issue, I will try make it today, but is quite a change.

Thank you to point that out.

Hope to see having fun using this library 😄

**Comment by calgara12** [comment]
Thanks :) no rush. just let me know once its fixed please :)

**Comment by pikax** [comment]
Sure

It will take a while, it will be a huge change in code and API

you can check my [v2 API vision](https://github.com/pikax/gin-downloader/tree/v2)

you are using javascript, probably you should check the cool stuff from es6/es2015  :)

**Comment by calgara12** [comment]
i will definitely do that :)

**Comment by calgara12** [comment]
Hey, did you get the chance to fix this problem, or will it still take some time? :)

**Comment by pikax** [comment]
just published [1.1.0](https://www.npmjs.com/package/gin-downloader) with the fix, but you need to change a bit of code.

Before I was trying to resolve all promises at once, now I'm returning a objecting with lazy loading pattern, that means only when you do *.value* it will create a promise therefore you will not have the same issue :)


*images(manga, chapter_number)* : return Promise<Promise<{value: {name:string,src:string}>[]>
```javascript
mangafox.images("Gintama", 1)
      .then(x=>Promise.all(x.map(t=>t.value))) //resolve all promises
      .then(console.log)
```

**Comment by calgara12** [comment]
Thank you,

But if i run your code i get: 
[output.txt](https://github.com/pikax/gin-downloader/files/1118007/output.txt)

thanks in advance. keep up the great work :)

**Comment by pikax** [comment]
try this 
```javascript

gin.mangafox.images("One Piece", 1)
  .then(x=>{
    console.log('starting...')
    console.log('getting %d images', x.length);
    return x.map(p=>{

      p.then(x=>x.value) //resole lazyload promise
        .then(r=>{
        //this will run as soon each promise is resolved
        //r contains url
        console.log(r);
      })
    });
  })
  .then(x=>Promise.all(x))
  .then(x=>console.log('resolved'))
  .catch(console.error);
```

**Comment by calgara12** [comment]
That does the trick! You are AWESOME :) Thanks!

**Comment by calgara12** [comment]
Unfortunately now i encounter the problem again, but this time i get the Image not found error for each image. Here is my output: 
[output.txt](https://github.com/pikax/gin-downloader/files/1132814/output.txt)
