### ISSUE TITLE
images function returning Array of "Promise {<pending>}"

### ISSUE THREAD

**Issue by calgara12** [pikax/gin-downloader#8]
I wanna start off with saying that i'm a total beginner when it comes to node js. Secondly i wanna thank you for your work, i really appreciate it. :) 
Here is my issue: First i wanted to follow your example code on the documentation. But i think you have a mistake there, shouldnt it be mangafox.images("Ginatama", 1)?
``` javascript
gin.mangafox.chapters("Gintama", 1)
        .then(Promise.all) //resolve all promises
        .then(console.log)
```

but even if i run it with images instead of chapters, i get the Error saying "Promise.all called on non-object"

i then tried a different approach:
``` javascript
    gin.mangafox.images("One Piece", 1).
          then(result =>{
        console.log(result);
    })
```
Which logs an array with "Promise {\<pending\>}" for each item. What am i doing wrong?
Thank you in advance and have a nice day! :)

**Comment by pikax** [comment]
Hi, 

The documentation is wrong I'm going to fix that ASAP.

The method **images** is returning `Promise<Promise<{name:string, src:string}>>` 

That means the first then is to resolve the Promise<[]>, but that array is an array of promises.

to get the result when it finishes 
``` javascript
//mangapanda is faster to get the results 

gin.mangapanda.images("One Piece", 1)
  .then(x=>Promise.all(x))
  .then(console.log)
```
or you can get a more interactive, it prints the result as soon as it gets resolved

```javascript
gin.mangafox.images("One Piece", 1)
  .then(x=>{
    console.log('starting...')
    console.log('getting %d images', x.length);
    return x.map(p=>{

      p.then(r=>{
        //this will run as soon each promise is resolved
        //r contains url
        console.log(r);
      })
    });
  })
  .then(x=>Promise.all(x))
  .then(x=>console.log('resolved'))
  .catch(console.error)
```


You have a cli version if you just want to download to a folder: [ginmanga-cli](https://github.com/pikax/ginmanga-cli) 

You can [join the chat at gitter](https://gitter.im/pikax/gin-downloader) if you have questions 👍 

Thank you :)

**Comment by calgara12** [comment]
Thank you so much, that fixed it! :)
